name: wash_test
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  excel: ^4.0.6
  firebase_storage: ^12.4.5
  firebase_analytics: ^11.4.5
  file_picker: ^10.1.1
  csv: ^6.0.0
  intl: ^0.20.2
  path_provider: ^2.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0

flutter:
  
  uses-material-design: true

  # assets:
  #   - assets/mycsv1.csv
